import { MagazineArticle } from "../../types";


export const articles: MagazineArticle[] = [
    {
      id: '1',
      title: '집콕 시대, 공간 효율 200% 만드는 정리·수납 공식 15가지',
      description:
        '작은 공간도 넓어 보이게 만드는 정리·수납 핵심 원리 15가지. 동선 설계부터 물건 배치, 숨은 공간 활용까지 한 번에 정리했습니다.',
      thumbnailUrl: '/images/blog/blog1.png',
      publishedAt: '2024-04-01',
      category: '정리·수납',
      author: '씩씩이',
      readTime: 10,
    },
    {
      id: '2',
      title: '쇼핑 실패 줄이는 법: 사람들이 가장 많이 후회하는 구매 10가지',
      description:
        '사람들이 가장 많이 후회하는 집안용품과 가전 구매 사례를 분석해, 무엇을 피해야 하고 무엇을 고려해야 하는지 기준을 알려드립니다.',
      thumbnailUrl: '/images/blog/blog2.png',
      publishedAt: '2024-04-04',
      category: '생활 지식',
      author: '아리',
      readTime: 8,
    },
    {
      id: '3',
      title: '겨울 난방비 아끼는 현실적인 방법 12가지: 덜 틀고도 덜 춥게 사는 법',
      description:
        '보일러 온도 설정, 단열, 창문 관리, 습도 조절 등 난방비를 실제로 줄이는 실전 방법 12가지를 정리했습니다.',
      thumbnailUrl: '/images/blog/blog3.png',
      publishedAt: '2024-04-07',
      category: '생활 꿀팁',
      author: '씩씩이',
      readTime: 9,
    },
    {
      id: '4',
      title: '조명만 바꿔도 집 분위기가 달라지는 이유: 공간을 따뜻하게 만드는 조명 배치 공식',
      description:
        '전구 색온도, 배치, 높이만 바꿔도 공간 분위기가 바뀝니다. 집을 따뜻하게 만드는 조명 배치 공식을 담았습니다.',
      thumbnailUrl: '/images/blog/blog4.png',
      publishedAt: '2024-04-10',
      category: '인테리어',
      author: '아리',
      readTime: 8,
    },
    {
      id: '5',
      title: '미니멀 라이프 시작하기: 물건보다 마음을 가볍게 만드는 정리 심리학과 실천 전략',
      description:
        '미니멀리즘은 단순히 물건을 줄이는 것이 아니라, 스트레스와 불안을 줄이는 심리적 구조입니다. 실전 적용법까지 정리했습니다.',
      thumbnailUrl: '/images/blog/blog5.png',
      publishedAt: '2024-04-13',
      category: '정리·수납',
      author: '씩씩이',
      readTime: 10,
    },
    {
      id: '6',
      title: '계절별 집 꾸미기 공식: 봄·여름·가을·겨울 인테리어가 달라지면 삶의 리듬도 달라진다',
      description:
        '계절에 따라 채광, 패브릭, 색감, 향, 가구 배치를 바꾸는 공식. 집안 분위기를 4계절마다 새롭게 만드는 방법.',
      thumbnailUrl: '/images/blog/blog6.png',
      publishedAt: '2024-04-16',
      category: '인테리어',
      author: '아리',
      readTime: 9,
    },
    {
      id: '7',
      title: '생활 꿀팁 20가지: 집안일이 가벼워지는 아주 현실적인 방법들',
      description:
        '청소, 세탁, 요리, 정리 등 일상 루틴을 가볍게 만들어주는 가장 현실적인 생활 꿀팁 20가지를 정리했습니다.',
      thumbnailUrl: '/images/blog/blog7.png',
      publishedAt: '2024-04-19',
      category: '생활 꿀팁',
      author: '씩씩이',
      readTime: 7,
    },
    {
      id: '8',
      title: '집 안 공기정화 완전 가이드: 환기, 습도, 미세먼지, 곰팡이까지 한 번에 정리',
      description:
        '환기 루틴, 제습·가습 밸런스, 미세먼지 관리, 곰팡이 예방까지 집 공기질을 가장 쉽게 관리하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog8.png',
      publishedAt: '2024-04-22',
      category: '건강한 집',
      author: '아리',
      readTime: 9,
    },
    {
      id: '9',
      title: '아침 루틴 완전 가이드: 집중력·기분·생활 리듬이 달라지는 12가지 현실 루틴',
      description:
        '아침을 어떻게 보내느냐에 따라 하루의 집중력과 스트레스가 달라집니다. 누구나 바로 따라할 수 있는 12가지 현실 루틴.',
      thumbnailUrl: '/images/blog/blog9.png',
      publishedAt: '2024-04-25',
      category: '라이프스타일',
      author: '씩씩이',
      readTime: 8,
    },
    {
      id: '10',
      title: '집안 냄새 완전 정복: 공간별 원인과 해결법 20가지',
      description:
        '현관·부엌·욕실·옷장·거실 등 공간별 냄새 원인과 해결법을 과학적으로 정리한 실전 관리 가이드입니다.',
      thumbnailUrl: '/images/blog/blog10.png',
      publishedAt: '2024-04-28',
      category: '생활 꿀팁',
      author: '아리',
      readTime: 10,
    },
    {
      id: '11',
      title: '청소 루틴 설계 가이드: 매일·주간·월간 청소를 쉽게 만드는 현실 전략',
      description:
        '집을 늘 깔끔하게 유지하는 사람들의 청소 루틴을 해부해, 누구나 지속할 수 있는 현실적인 시스템으로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog11.png',
      publishedAt: '2024-05-01',
      category: '생활 정리',
      author: '씩씩이',
      readTime: 9,
    },
    {
      id: '12',
      title: '식물 별 분갈이 시기 & 분갈이 방법 완벽 가이드',
      description:
        '초보자도 실패 없이 분갈이를 할 수 있도록 계절별 시기, 흙 고르는 법, 뿌리 정리 팁, 난이도별 식물 분갈이 방법까지 모두 정리했습니다.',
      thumbnailUrl: '/images/blog/blog12.png',
      publishedAt: '2024-05-04',
      category: '식물 관리',
      author: '아리',
      readTime: 8,
    },
    {
      id: '13',
      title: '겨울철 야외활동 전 꼭 알아야 할 안전 수칙 12가지',
      description:
        '빙판길 낙상부터 저체온증, 배터리 방전, 차량 고립까지. 겨울 야외활동에서 실제로 자주 발생하는 위험을 예방하는 12가지 안전 수칙을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog13.png',
      publishedAt: '2024-05-07',
      category: '겨울 안전',
      author: '씩씩이',
      readTime: 9,
    },
    {
      id: '14',
      title: '연말·크리스마스 데이트가 망하지 않는 12가지 체크리스트',
      description:
        '사람 많은 날일수록 계획이 곧 안전이자 재미입니다. 예약/동선/대기/예산/사진 포인트까지 연말 데이트를 실패 없이 굴리는 12가지 체크리스트를 정리했습니다.',
      thumbnailUrl: '/images/blog/blog14.png',
      publishedAt: '2024-05-10',
      category: '데이트·이벤트',
      author: '아리',
      readTime: 9,
    },
    {
      id: '15',
      title: '겨울 산책·축제·데이트 안전 수칙 12가지: 미끄럼·저체온증·일몰 시간 체크리스트',
      description:
        '겨울 산책, 축제, 여행, 야외 데이트 전 반드시 체크해야 할 안전 수칙 12가지. 미끄럼·저체온증·탈수·일몰 시간까지 현실적인 기준으로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog15.png',
      publishedAt: '2024-05-13',
      category: '야외 안전',
      author: '씩씩이',
      readTime: 8,
    },
    {
      id: '16',
      title: '겨울 여행 전 체크리스트 25가지: 교통·숙소·짐·날씨 변수까지 한 번에',
      description:
        '겨울 여행은 준비가 반입니다. 도로 결빙, 지연, 숙소 난방, 방한 장비, 비상약, 일정 여유까지 “실수하기 쉬운 포인트”를 체크리스트로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog16.png',
      publishedAt: '2024-05-16',
      category: '겨울 여행',
      author: '아리',
      readTime: 9,
    },
    {
      id: '17',
      title: '겨울 데이트 코스 실패 없는 공식 10가지: 추위·대기·동선까지 설계하는 법',
      description:
        '겨울 데이트는 “추위/대기/이동” 변수가 커서 코스 설계가 중요합니다. 실패 확률을 낮추는 동선 공식 10가지를 실제 예시와 함께 정리했습니다.',
      thumbnailUrl: '/images/blog/blog17.png',
      publishedAt: '2024-05-19',
      category: '데이트·이벤트',
      author: '씩씩이',
      readTime: 9,
    },
    {
      id: '18',
      title: '겨울 야외활동 안전 체크리스트 12가지: 일산화탄소·야간 시야·빙판길 대비',
      description:
        '빙판길·저체온증·일산화탄소·야간 시야 등 겨울 야외활동에서 자주 발생하는 위험을 줄이는 실전 안전 수칙 12가지를 체크리스트로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog18.png',
      publishedAt: '2024-05-22',
      category: '야외 안전',
      author: '아리',
      readTime: 9,
    },
    {
      id: '19',
      title: '크리스마스·연말 이벤트 200% 즐기는 체크리스트 15가지: 약속, 선물, 장소, 예산까지',
      description:
        '크리스마스/연말에 "뭘 해야 하지?" 고민을 줄여주는 실전 체크리스트 15가지. 데이트·친구·가족 모임까지 상황별로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog19.png',
      publishedAt: '2024-05-25',
      category: '이벤트·데이트',
      author: '씩씩이',
      readTime: 10,
    },
    {
      id: '20',
      title: '기내식에 삶은 채소와 과일이 많이 등장하는 이유는?',
      description:
        '기내식 메뉴에 삶은 채소와 과일이 자주 등장하는 과학적인 이유를 알아봅니다. 고공에서 변화하는 후각과 미각, 식품 안전성, 식감 유지까지 기내식 메뉴 설계의 비밀을 풀어봅니다.',
      thumbnailUrl: '/images/blog/blog20.png',
      publishedAt: '2024-11-25',
      category: '식품 과학',
      author: '씩씩이',
      readTime: 8,
    },
    {
      id: '21',
      title: '시나몬과 계피, 무엇이 다른가요?',
      description:
        '시나몬과 계피의 차이점을 알아봅니다. 나무 품종, 향미 성분, 외관, 보관법부터 쿠마린 함량과 건강 주의사항까지, 두 향신료를 올바르게 구별하고 사용하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog21.png',
      publishedAt: '2024-11-10',
      category: '식품 과학',
      author: '씩씩이',
      readTime: 8,
    },
    {
      id: '22',
      title: '가래떡 찍어먹을 때, 조청 VS 물엿',
      description:
        '가래떡에 찍어먹는 조청과 물엿의 차이점을 알아봅니다. 제조 공정, 맛과 향, 용도부터 건강한 섭취 방법까지, 두 시럽을 올바르게 구별하고 선택하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog22.png',
      publishedAt: '2024-11-11',
      category: '식품 과학',
      author: '씩씩이',
      readTime: 8,
    },
    {
      id: '23',
      title: '2026년 1인 사업자 종합소득세 신고 방법 - 홈택스로 직접 하는 완벽 가이드',
      description: '2026년 1인 사업자 종합소득세 신고 방법을 단계별로 정리했습니다. 홈택스 셀프 신고부터 절세 팁까지.',
      thumbnailUrl: '/images/blog/blog23.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
      {
      id: '24',
      title: 'ChatGPT 무료 vs 유료(Plus) 차이 - 2026년 기준 완벽 비교',
      description: 'ChatGPT 무료와 유료 Plus의 실제 차이를 비교합니다. 속도, 기능, 모델, 가격 대비 가치까지.',
      thumbnailUrl: '/images/blog/blog24.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '25',
      title: '2026 무선청소기 추천 가성비 TOP 5 - 실사용 기준 비교',
      description: '2026년 가성비 무선청소기 추천 5가지를 흡입력, 배터리, 무게 기준으로 비교했습니다.',
      thumbnailUrl: '/images/blog/blog25.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '26',
      title: '2026년 현실적인 부업 추천 7가지 - 직장인도 가능한 N잡 정리',
      description: '2026년 현실적으로 돈 되는 부업 7가지를 수익, 난이도, 시간 투자별로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog26.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '23',
      title: '2026년 1인 사업자 종합소득세 신고 방법 - 홈택스로 직접 하는 완벽 가이드',
      description: '2026년 1인 사업자 종합소득세 신고 방법을 단계별로 정리했습니다. 홈택스 셀프 신고부터 절세 팁까지.',
      thumbnailUrl: '/images/blog/blog23.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '24',
      title: 'ChatGPT 무료 vs 유료(Plus) 차이 - 2026년 기준 완벽 비교',
      description: 'ChatGPT 무료와 유료 Plus의 실제 차이를 비교합니다. 속도, 기능, 모델, 가격 대비 가치까지.',
      thumbnailUrl: '/images/blog/blog24.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '25',
      title: '2026 무선청소기 추천 가성비 TOP 5 - 실사용 기준 비교',
      description: '2026년 가성비 무선청소기 추천 5가지를 흡입력, 배터리, 무게 기준으로 비교했습니다.',
      thumbnailUrl: '/images/blog/blog25.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '26',
      title: '2026년 현실적인 부업 추천 7가지 - 직장인도 가능한 N잡 정리',
      description: '2026년 현실적으로 돈 되는 부업 7가지를 수익, 난이도, 시간 투자별로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog26.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '23',
      title: '2026년 1인 사업자 종합소득세 신고 방법 - 홈택스로 직접 하는 완벽 가이드',
      description: '2026년 1인 사업자 종합소득세 신고 방법을 단계별로 정리했습니다. 홈택스 셀프 신고부터 절세 팁까지.',
      thumbnailUrl: '/images/blog/blog23.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '24',
      title: 'ChatGPT 무료 vs 유료(Plus) 차이 - 2026년 기준 완벽 비교',
      description: 'ChatGPT 무료와 유료 Plus의 실제 차이를 비교합니다. 속도, 기능, 모델, 가격 대비 가치까지.',
      thumbnailUrl: '/images/blog/blog24.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '25',
      title: '2026 무선청소기 추천 가성비 TOP 5 - 실사용 기준 비교',
      description: '2026년 가성비 무선청소기 추천 5가지를 흡입력, 배터리, 무게 기준으로 비교했습니다.',
      thumbnailUrl: '/images/blog/blog25.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '26',
      title: '2026년 현실적인 부업 추천 7가지 - 직장인도 가능한 N잡 정리',
      description: '2026년 현실적으로 돈 되는 부업 7가지를 수익, 난이도, 시간 투자별로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog26.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '27',
      title: 'Claude vs ChatGPT 2026년 비교',
      description: 'Claude와 ChatGPT 차이점을 실사용 기준으로 비교합니다.',
      thumbnailUrl: '/images/blog/blog27.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '28',
      title: 'AI로 블로그 글 쓰는 현실적인 방법',
      description: 'AI를 활용해 블로그 글을 효율적으로 작성하는 실전 가이드입니다.',
      thumbnailUrl: '/images/blog/blog28.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '29',
      title: '노코드 앱 만들기 2026 가이드',
      description: '코딩 없이 앱을 만드는 노코드 플랫폼 비교 가이드입니다.',
      thumbnailUrl: '/images/blog/blog29.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '30',
      title: '맥북 vs 윈도우 노트북 2026 비교',
      description: '맥북과 윈도우 노트북 장단점을 현실적으로 비교합니다.',
      thumbnailUrl: '/images/blog/blog30.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '31',
      title: 'VPN 추천 2026 무료 유료 비교',
      description: '2026년 VPN 서비스 추천과 무료/유료 차이를 비교합니다.',
      thumbnailUrl: '/images/blog/blog31.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '32',
      title: '스마트홈 입문 가이드 2026',
      description: '스마트홈을 시작하는 방법을 단계별로 안내합니다.',
      thumbnailUrl: '/images/blog/blog32.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '33',
      title: '아이폰 vs 갤럭시 2026 솔직 비교',
      description: '아이폰과 갤럭시 장단점을 솔직하게 비교합니다.',
      thumbnailUrl: '/images/blog/blog33.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '34',
      title: '유튜브 프리미엄 가치가 있을까',
      description: '유튜브 프리미엄 구독 가치를 분석합니다.',
      thumbnailUrl: '/images/blog/blog34.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '35',
      title: '2026 태블릿 추천 용도별 정리',
      description: '용도별 태블릿 추천 가이드입니다. 아이패드, 갤럭시탭 비교.',
      thumbnailUrl: '/images/blog/blog35.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '36',
      title: '코딩 독학 로드맵 2026',
      description: '프로그래밍을 독학하는 현실적인 로드맵을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog36.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '37',
      title: '2026 무선 이어폰 추천 가성비 TOP 5',
      description: '가성비 무선 이어폰 추천 5가지를 비교합니다.',
      thumbnailUrl: '/images/blog/blog37.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '38',
      title: '생산성 앱 추천 TOP 7',
      description: '업무 생산성을 높여주는 앱 7가지를 추천합니다.',
      thumbnailUrl: '/images/blog/blog38.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '39',
      title: '클라우드 저장소 비교 2026',
      description: '구글 드라이브, 원드라이브, 아이클라우드 비교 가이드입니다.',
      thumbnailUrl: '/images/blog/blog39.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '40',
      title: '비밀번호 관리 앱 추천',
      description: '비밀번호 관리 앱 비교와 추천 가이드입니다.',
      thumbnailUrl: '/images/blog/blog40.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '41',
      title: 'AI 이미지 생성 도구 비교 2026',
      description: 'AI 이미지 생성 도구를 비교하고 용도별 추천합니다.',
      thumbnailUrl: '/images/blog/blog41.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '42',
      title: '넷플릭스 vs 티빙 vs 웨이브 비교',
      description: 'OTT 서비스 3개를 비교하고 추천합니다.',
      thumbnailUrl: '/images/blog/blog42.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '43',
      title: '2026 모니터 추천 재택근무용',
      description: '재택근무에 적합한 모니터를 예산별로 추천합니다.',
      thumbnailUrl: '/images/blog/blog43.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '44',
      title: '2026 키보드 추천 사무용 TOP 5',
      description: '사무실/재택에서 쓰기 좋은 키보드 추천입니다.',
      thumbnailUrl: '/images/blog/blog44.png',
      publishedAt: '2026-04-27',
      category: 'AI/테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '45',
      title: '공기청정기 추천 2026 TOP 5',
      description: '2026년 가성비 공기청정기 추천 5가지를 비교합니다.',
      thumbnailUrl: '/images/blog/blog45.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '46',
      title: '전기요금 아끼는 방법 15가지',
      description: '전기요금을 현실적으로 줄이는 방법 15가지를 정리했습니다.',
      thumbnailUrl: '/images/blog/blog46.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '47',
      title: '냉장고 정리 수납 방법',
      description: '냉장고를 깔끔하게 정리하는 수납 방법을 소개합니다.',
      thumbnailUrl: '/images/blog/blog47.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '48',
      title: '세탁기 사용법 제대로 알기',
      description: '세탁기를 효율적으로 사용하는 방법과 팁을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog48.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '49',
      title: '다이소 꼭 사야 할 생활용품 20선',
      description: '다이소에서 꼭 사야 할 가성비 생활용품 20가지를 추천합니다.',
      thumbnailUrl: '/images/blog/blog49.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '50',
      title: '이사 체크리스트 완벽 정리',
      description: '이사할 때 빠뜨리기 쉬운 것들을 체크리스트로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog50.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '51',
      title: '올바른 분리수거 방법 가이드',
      description: '헷갈리는 분리수거 방법을 확실하게 정리했습니다.',
      thumbnailUrl: '/images/blog/blog51.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '52',
      title: '홈카페 커피 내리는 법 입문',
      description: '집에서 커피를 맛있게 내리는 방법을 초보자 기준으로 정리했습니다.',
      thumbnailUrl: '/images/blog/blog52.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '53',
      title: '반려식물 초보 가이드 TOP 10',
      description: '키우기 쉬운 반려식물 10가지를 추천합니다.',
      thumbnailUrl: '/images/blog/blog53.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '54',
      title: '여름 냉방비 아끼는 에어컨 사용법',
      description: '에어컨 전기요금을 줄이는 실전 사용법입니다.',
      thumbnailUrl: '/images/blog/blog54.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '55',
      title: '식기세척기 사야 할까 솔직 후기',
      description: '식기세척기 구매 전 알아야 할 장단점을 솔직하게 정리했습니다.',
      thumbnailUrl: '/images/blog/blog55.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '56',
      title: '수면의 질 높이는 방법 10가지',
      description: '잠을 더 잘 자기 위한 현실적인 방법 10가지입니다.',
      thumbnailUrl: '/images/blog/blog56.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '57',
      title: '1인 가구 장보기 가이드',
      description: '1인 가구가 식비를 아끼면서 장보는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog57.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '58',
      title: '겨울 난방비 줄이는 현실적인 방법',
      description: '겨울 난방비를 현실적으로 줄이는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog58.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '59',
      title: '청소 루틴 만들기 주간 가이드',
      description: '매일 10분 청소로 집을 깨끗하게 유지하는 방법입니다.',
      thumbnailUrl: '/images/blog/blog59.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '60',
      title: '택배 박스 활용법 10가지',
      description: '버리기 아까운 택배 박스 활용법 10가지를 소개합니다.',
      thumbnailUrl: '/images/blog/blog60.png',
      publishedAt: '2026-04-27',
      category: '생활용품',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '61',
      title: '월급 관리 방법 통장 쪼개기',
      description: '월급을 효율적으로 관리하는 통장 쪼개기 방법입니다.',
      thumbnailUrl: '/images/blog/blog61.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '62',
      title: 'ETF 투자 입문 가이드',
      description: 'ETF 투자를 시작하는 방법을 초보자 기준으로 설명합니다.',
      thumbnailUrl: '/images/blog/blog62.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '63',
      title: '신용점수 올리는 방법 정리',
      description: '신용점수를 올리는 현실적인 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog63.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '64',
      title: '프리랜서 세금 신고 가이드',
      description: '프리랜서/N잡러를 위한 세금 신고 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog64.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '65',
      title: '적금 vs 예금 차이와 추천',
      description: '적금과 예금의 차이점을 설명하고 상황별 추천합니다.',
      thumbnailUrl: '/images/blog/blog65.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '66',
      title: '생활비 절약 실전 방법 20가지',
      description: '실제로 효과가 있는 생활비 절약 방법 20가지입니다.',
      thumbnailUrl: '/images/blog/blog66.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '67',
      title: '중고거래 잘하는 방법 팁',
      description: '당근마켓/번개장터에서 중고거래 잘하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog67.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '68',
      title: '보험 이것만 있으면 된다',
      description: '필수 보험과 불필요한 보험을 구분하는 가이드입니다.',
      thumbnailUrl: '/images/blog/blog68.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '69',
      title: '연말정산 환급 많이 받는 법',
      description: '연말정산에서 환급을 최대화하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog69.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '70',
      title: '20대 재테크 시작 가이드',
      description: '20대가 알아야 할 재테크 기초를 정리했습니다.',
      thumbnailUrl: '/images/blog/blog70.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '71',
      title: '부동산 전월세 계약 시 주의할 점',
      description: '전월세 계약할 때 꼭 확인해야 할 사항을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog71.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '72',
      title: '자동차 유지비 줄이는 방법',
      description: '자동차 유지비를 현실적으로 줄이는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog72.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '73',
      title: '쿠팡파트너스 시작 가이드',
      description: '쿠팡파트너스로 부수입을 만드는 방법을 단계별로 설명합니다.',
      thumbnailUrl: '/images/blog/blog73.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '74',
      title: '주린이 주식 입문 가이드',
      description: '주식 투자를 처음 시작하는 사람을 위한 가이드입니다.',
      thumbnailUrl: '/images/blog/blog74.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
    {
      id: '75',
      title: '카드 포인트 활용법 정리',
      description: '카드 포인트를 최대로 활용하는 방법을 정리했습니다.',
      thumbnailUrl: '/images/blog/blog75.png',
      publishedAt: '2026-04-27',
      category: '재테크',
      author: '씩씩이',
      readTime: 5,
    },
]